// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGSWeb.EF;

namespace SGSWeb.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SGSWeb.Core.Models.BonusTbl", b =>
                {
                    b.Property<int>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepID")
                        .HasColumnType("int");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("JDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<decimal?>("Performanse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sarlary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("depTblDepID")
                        .HasColumnType("int");

                    b.HasKey("EmpID");

                    b.HasIndex("depTblDepID");

                    b.ToTable("bonusTbls");
                });

            modelBuilder.Entity("SGSWeb.Core.Models.DepTbl", b =>
                {
                    b.Property<int>("DepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepNAme")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DepID");

                    b.ToTable("depTbls");
                });

            modelBuilder.Entity("SGSWeb.Core.Models.BonusTbl", b =>
                {
                    b.HasOne("SGSWeb.Core.Models.DepTbl", "depTbl")
                        .WithMany()
                        .HasForeignKey("depTblDepID");

                    b.Navigation("depTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
